version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: 4dm1nus3r
      WORDPRESS_DB_PASSWORD: p4ss
      WORDPRESS_DB_NAME: admin
    volumes:
      - wordpress:/var/www/html

  wordpressdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: 4dm1nus3r
      MYSQL_PASSWORD: p4ss
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpressdb:/var/lib/mysql

volumes:
  wordpress:
  wordpressdb: